version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
  cache:
    image: memcached:1.6.17
    restart: always
    ports:
      - '11211:11211'
