name: Rspec
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: CI
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install -y libmysqlclient-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Verify MySQL connection from host
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
      - name: Setup DB
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:root@127.0.0.1:${{ job.services.mysql.ports[3306] }}/sara_test
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'yarn'
      - name: Configure Yarn
        run: |
          yarn set version berry
          yarn config set nodeLinker node-modules
      - name: Build Assets
        run: |
          yarn install --no-immutable
          rake assets:precompile
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:root@127.0.0.1:${{ job.services.mysql.ports[3306] }}/sara_test
        run: |
          bundle exec rspec
